#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -f ".nvmrc" ] && [ -z "$(node --version 2>/dev/null)" ]; then
  echo "==> Installing specified version..."
  cat .nvmrc | nvm install $1
fi

if [ -f "package.json" ] then
  echo "==> Installing Homebrew dependencies…"
  npm ci
fi

