#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

# ensure everything in the app is up to date.
script/update

test -z "$APP_ENV" &&
  APP_ENV='development'

PORT=3000

# boot the app and any other necessary processes.
nodemon start -p $PORT
